version: 2.1     
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout:
          path: ~/checkout

      - setup_remote_docker
      
      - run:
          name: echo
          command: echo $DOCKER_USER
      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: build dockerfile
          command: |
            docker build -t vawu/send-card:Build-${CIRCLE_BUILD_NUM}-CI .
      - run: 
          name: push to dockerhub
          command: |
            docker push vawu/send-card:Build-${CIRCLE_BUILD_NUM}-CI
      - run: 
          name: tag and push
          command: |
            docker tag vawu/send-card:Build-${CIRCLE_BUILD_NUM}-CI vawu/<< parameters.service-name >>:latest
            docker push vawu/send-card:latest    
      - store_artifacts:
          path: target
          destination: target-sendcard